version: "3.9"
services:
  pg_db:
    image: postgres:latest
    container_name: pg_db
    environment: # see .env file (default for docker-compose)
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    volumes: # preserves all data between executions
      - pg_database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - app_db

  app:
    container_name: rent_it_api
    build:
      context: .
      labels:
        - "com.rent-it.app=API for rent-it applications"
    ports:
    - 8080:8080
    expose:
      - 8080
    networks:
      - app_db
    depends_on:
      - pg_db

volumes:
  pg_database:

networks:
  app_db: # enable networking between db and app containers
    driver: bridge